"use client";

import React, { useState } from "react";
import { ParquetDataset } from "@/lib/parquet-engine";
import { Code2, Copy, Check, Terminal, FileCode2, BookOpen } from "lucide-react";

interface CodeSnippetsModalProps {
  dataset: ParquetDataset;
}

export const CodeSnippetsModal: React.FC<CodeSnippetsModalProps> = ({ dataset }) => {
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const filename = dataset.filename || "train-00000-of-00001.parquet";

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const pythonPandasCode = `import pandas as pd

# Load the Parquet dataset generated by Devcart Technologies Studio
df = pd.read_parquet("${filename}")

# Inspect rows & schema
print(f"Loaded {len(df)} records with columns: {list(df.columns)}")
print(df.head())
`;

  const huggingFaceCode = `from datasets import load_dataset

# Load directly into Hugging Face Datasets format
dataset = load_dataset("parquet", data_files={"train": "${filename}"})

print(dataset)
sample = dataset["train"][0]
print("First Sample Ground Truth:", sample.get("ground_truth", sample.get("text")))
`;

  const trocrPytorchCode = `import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from PIL import Image
import io
import base64

class OCRDataset(Dataset):
    def __init__(self, parquet_path):
        self.df = pd.read_parquet(parquet_path)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        ground_truth = row.get("ground_truth", "")
        
        # Load image bytes/base64
        img_data = row.get("image")
        if isinstance(img_data, dict) and "src" in img_data:
            b64_str = img_data["src"].split(",")[-1]
            img_bytes = base64.b64decode(b64_str)
            image = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        else:
            image = Image.new("RGB", (480, 280), color=(255, 255, 255))
            
        return {"image": image, "text": ground_truth}

# Instantiate DataLoader
train_dataset = OCRDataset("${filename}")
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
print(f"Dataset ready with {len(train_dataset)} samples!")
`;

  const huggingFacePushCode = `# Push dataset directly to Hugging Face Hub
from datasets import load_dataset

dataset = load_dataset("parquet", data_files={"train": "${filename}"})

# Upload to your Hugging Face organization
dataset.push_to_hub("username/ocr-dataset-${filename.replace('.parquet', '')}")
print("Successfully pushed to Hugging Face Hub!")
`;

  const snippets = [
    {
      key: "hf",
      title: "Hugging Face Datasets",
      desc: "Standard load_dataset() call for Hugging Face NLP / Vision",
      code: huggingFaceCode,
    },
    {
      key: "pandas",
      title: "Python Pandas",
      desc: "Fast DataFrame read with pd.read_parquet()",
      code: pythonPandasCode,
    },
    {
      key: "pytorch",
      title: "PyTorch OCR Dataset & DataLoader",
      desc: "Ready-to-train PyTorch custom Dataset for Vision OCR / TrOCR / Donut",
      code: trocrPytorchCode,
    },
    {
      key: "hub",
      title: "Push to Hugging Face Hub",
      desc: "Upload the created Parquet file directly to HF Hub",
      code: huggingFacePushCode,
    },
  ];

  return (
    <div className="w-full space-y-6">
      {/* Header */}
      <div className="p-6 rounded-2xl glass-card border border-slate-800 shadow-xl flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-600 to-blue-700 flex items-center justify-center text-white shadow-lg shadow-cyan-500/20">
            <Code2 className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">
              Python, PyTorch & Hugging Face Code Integration
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Copy-paste code snippets to load and train models on <span className="text-cyan-400 font-mono">{filename}</span>
            </p>
          </div>
        </div>
      </div>

      {/* Snippets List */}
      <div className="grid grid-cols-1 gap-6">
        {snippets.map((snip) => (
          <div
            key={snip.key}
            className="rounded-2xl glass-card border border-slate-800 overflow-hidden shadow-xl"
          >
            <div className="p-3.5 bg-slate-900/90 border-b border-slate-800 flex items-center justify-between">
              <div>
                <h3 className="text-xs font-bold text-white font-mono">{snip.title}</h3>
                <p className="text-[11px] text-slate-400">{snip.desc}</p>
              </div>

              <button
                onClick={() => copyToClipboard(snip.code, snip.key)}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition"
              >
                {copiedKey === snip.key ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-slate-400" />
                    <span>Copy Code</span>
                  </>
                )}
              </button>
            </div>

            <div className="p-4 bg-slate-950 font-mono text-xs text-slate-200 overflow-x-auto">
              <pre className="text-cyan-300 leading-relaxed">{snip.code}</pre>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
